### ISSUE TITLE
Internalize Employers contact form

### ISSUE THREAD

**Issue by db0sch** [lewagon/www#522]
**Today:** Typeform (created by Tatiana), connected to Zapier and then push data to the `#hiring` Slack channel

**Future:** To have our own form in `www` to push information to the Slack `#hiring` channel. Ditch Typeform + Zapier

Questions in the Typeform: 
- First Name
- Last Name
- Email
- Phone Number
- Company
- Company's website
- What are you looking for?
  a. FullStack developer (ruby / Rails)
  b. Front-end developer
  c. Product manager
  d. Growth marketer
  e. Technical sales
  f. Other
- In which city(ies) would you like to meet our community?
 a. Paris
 b. Tokyo
 c. Shanghai
 d. ...
- Why do you want to recruit Le Wagon's alumni?

Questions for Tatiana:
- Need more questions?
- All mandatory?
- Typeform style (animation)?
- Redirect where?
- Any other improvments?
- How does we use the data ?
- Do we need to store the data somewhere?

Message example send to `#hiring` slack:
👇 
**Person:** Enzo Zadrima - enzo@equipmentconnect.co.uk - 020 3950 1545
**Company :** EquipmentConnect
**Company Website:** http://www.equipmentconnect.co.uk
**Why:** We are looking for humble people willing to constantly learn new things and with the passion for building secure and reliable applications.
**Which city:** London
**Looking for:** Front-end developer
☝️ 

JSON formatted text for Slack:
```
{
    "text": "*Person:* Enzo Zadrima - enzo@equipmentconnect.co.uk - 020 3950 1545\n*Company:* EquipmentConnect\n*Company Website:* http://www.equipmentconnect.co.uk\n*Why:* We are looking for humble people willing to constantly learn new things and with the passion for building secure and reliable applications.\n*Which city:* London\n*Looking for:* Front-end developer"
}
```

Get the slack webhook URL credential

Incoming Webhook documentation: https://api.slack.com/incoming-webhooks

Form example: 
https://codepen.io/arcs/pen/OmZaex
https://codepen.io/drew_mc/pen/ZGGErL

Create a EmployerContact model (without ActiveRecord)
And create a `notify_slack` method which will call the `NotifySlack` job (with `perform_later`)
just like in `prospect.rb`

**TODO**:
- [ ] Contact Form
- [ ] Internal logic (Routes, Controller)
- [ ] Create a EmployerContact object to encapsulate the form data
- [ ] notify_slack method to send data to `#hiring`
- [ ] Integration tests (form ...)

**Comment by db0sch** [comment]
Solved in #530
